#!/bin/sh

scripts/setup_common.py --full-name="cdb" \
                        --cross-compile="aarch64-oe-linux-" \
                        --arch-name="arm64" \
                        --target-name="cdb" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/arm64/configs/somc_tone_cdb_defconfig" \
                        --build-instruction="make" \
                        --image="arch/arm64/boot/Image.gz" \
                        "$@"
