#!/bin/sh

scripts/setup_common.py --full-name="hikey" \
                        --cross-compile="aarch64-linux-gnu-" \
                        --arch-name="arm64" \
                        --target-name="hikey" \
                        --fixup-kernel-headers="scripts/kernel_headers/default.fixup" \
                        --defconfig-base="arch/arm64/configs/hikey_defconfig" \
                        --build-instruction="make" \
                        --image="arch/arm64/boot/Image" \
                        "$@"
